# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui',
# licensing of 'main.ui' applies.
#
# Created: Fri Jun 14 09:37:31 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(694, 408)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainForm.sizePolicy().hasHeightForWidth())
        MainForm.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrotButton = QtWidgets.QPushButton(MainForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrotButton.sizePolicy().hasHeightForWidth())
        self.scrotButton.setSizePolicy(sizePolicy)
        self.scrotButton.setObjectName("scrotButton")
        self.horizontalLayout_2.addWidget(self.scrotButton)
        self.settingButton = QtWidgets.QPushButton(MainForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingButton.sizePolicy().hasHeightForWidth())
        self.settingButton.setSizePolicy(sizePolicy)
        self.settingButton.setObjectName("settingButton")
        self.horizontalLayout_2.addWidget(self.settingButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(MainForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 64))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 30, 566, 24))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rad_1 = QtWidgets.QRadioButton(self.layoutWidget)
        self.rad_1.setObjectName("rad_1")
        self.typeBtnGroup = QtWidgets.QButtonGroup(MainForm)
        self.typeBtnGroup.setObjectName("typeBtnGroup")
        self.typeBtnGroup.addButton(self.rad_1)
        self.horizontalLayout.addWidget(self.rad_1)
        self.rad_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.rad_2.setObjectName("rad_2")
        self.typeBtnGroup.addButton(self.rad_2)
        self.horizontalLayout.addWidget(self.rad_2)
        self.rad_3 = QtWidgets.QRadioButton(self.layoutWidget)
        self.rad_3.setObjectName("rad_3")
        self.typeBtnGroup.addButton(self.rad_3)
        self.horizontalLayout.addWidget(self.rad_3)
        self.rad_4 = QtWidgets.QRadioButton(self.layoutWidget)
        self.rad_4.setObjectName("rad_4")
        self.typeBtnGroup.addButton(self.rad_4)
        self.horizontalLayout.addWidget(self.rad_4)
        self.rad_5 = QtWidgets.QRadioButton(self.layoutWidget)
        self.rad_5.setObjectName("rad_5")
        self.typeBtnGroup.addButton(self.rad_5)
        self.horizontalLayout.addWidget(self.rad_5)
        self.rad_14 = QtWidgets.QRadioButton(self.layoutWidget)
        self.rad_14.setObjectName("rad_14")
        self.typeBtnGroup.addButton(self.rad_14)
        self.horizontalLayout.addWidget(self.rad_14)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.questLineEdit = QtWidgets.QLineEdit(MainForm)
        self.questLineEdit.setObjectName("questLineEdit")
        self.horizontalLayout_3.addWidget(self.questLineEdit)
        self.searchButton = QtWidgets.QPushButton(MainForm)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_3.addWidget(self.searchButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.textBrowser = QtWidgets.QTextBrowser(MainForm)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)

        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        MainForm.setWindowTitle(QtWidgets.QApplication.translate("MainForm", "智慧树辅助脚本", None, -1))
        self.scrotButton.setText(QtWidgets.QApplication.translate("MainForm", "选取", None, -1))
        self.settingButton.setText(QtWidgets.QApplication.translate("MainForm", "设置", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainForm", "题目类型", None, -1))
        self.rad_1.setText(QtWidgets.QApplication.translate("MainForm", "单选题", None, -1))
        self.rad_2.setText(QtWidgets.QApplication.translate("MainForm", "多选题", None, -1))
        self.rad_3.setText(QtWidgets.QApplication.translate("MainForm", "填空题", None, -1))
        self.rad_4.setText(QtWidgets.QApplication.translate("MainForm", "问答题", None, -1))
        self.rad_5.setText(QtWidgets.QApplication.translate("MainForm", "分析题/解答题/计算题/证明题", None, -1))
        self.rad_14.setText(QtWidgets.QApplication.translate("MainForm", "判断题", None, -1))
        self.searchButton.setText(QtWidgets.QApplication.translate("MainForm", "搜索", None, -1))

